/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

//https://www.parasoft.com/junit-tutorial-setting-up-writing-and-running-java-unit-tests/
//https://blog.jetbrains.com/idea/2020/09/writing-tests-with-junit-5/


}
